
#                   _   ___      _______  _   _
#       /\         | | (_) \    / /  __ \| \ | |
#      /  \   _ __ | |_ _ \ \  / /| |__) |  \| |
#     / /\ \ | '_ \| __| | \ \/ / |  ___/| . ` |
#    / ____ \| | | | |_| |  \  /  | |    | |\  |
#   /_/    \_\_| |_|\__|_|   \/   |_|    |_| \_|
#

debug:
  # If enabled, the plugin will print debug messages to players with the permission "AntiVPN.Debug".
  enabled: false